// Bundles each candidate's third-party dependencies into vendor/, and records
// what each one costs to download.
//
// The sizes here are the whole point of the exercise as much as the timings
// are: this app ships a WebAssembly runtime before it ships a single feature,
// so a visualisation library is spending from an already-overdrawn budget.
// Measuring the tree-shaken bundle rather than the package's advertised size
// matters — the gap between "d3" and the three d3 modules actually used is
// more than fivefold.
//
// GitHub Pages negotiates gzip but not brotli, so gzip is the number that
// decides anything. Brotli is recorded because a future move to a CDN or to
// Cloudflare Pages would make it the real one.

import { build } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { gzipSync, brotliCompressSync, constants } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const vendorDir = join(here, 'vendor');

// Each entry is the third-party surface one candidate needs, written as the
// candidate would import it. Anything the candidate hand-writes is not here —
// that is the candidate's own code and costs nothing extra to download.
const bundles = {
    // Layout only. The renderer, pan/zoom and mini-map are hand-written.
    'dagre': `export { layout as dagreLayout, graphlib } from 'dagre';`,

    // The reference option: d3 for the DAG layout and for rendering.
    'd3-dag': `
        export { select } from 'd3-selection';
        export { zoom, zoomIdentity } from 'd3-zoom';
        export { line, curveBumpY, curveLinear } from 'd3-shape';
        export { graph, graphStratify, sugiyama, layeringLongestPath, decrossTwoLayer, coordSimplex, coordGreedy }
            from 'd3-dag';
    `,

    // Batteries included: its own renderer, pan/zoom, and a mini-map extension.
    'cytoscape': `
        import cytoscape from 'cytoscape';
        import dagre from 'cytoscape-dagre';
        cytoscape.use(dagre);
        export { cytoscape };
    `,

    // Layered layout with the best quality of the four, and by far the worst
    // download cost. Bundled to confirm the number rather than to trust it.
    'elk': `
        import ELK from 'elkjs/lib/elk.bundled.js';
        export { ELK };
    `,
};

await mkdir(vendorDir, { recursive: true });

const report = {};
for (const [name, source] of Object.entries(bundles)) {
    const entry = join(vendorDir, `.entry-${name}.js`);
    await writeFile(entry, source);

    const outfile = join(vendorDir, `${name}.js`);
    await build({
        entryPoints: [entry],
        outfile,
        bundle: true,
        minify: true,
        format: 'esm',
        target: 'es2022',
        logLevel: 'error',
    });

    const bytes = await readFile(outfile);
    report[name] = {
        minified: bytes.length,
        gzip: gzipSync(bytes, { level: 9 }).length,
        brotli: brotliCompressSync(bytes, {
            params: { [constants.BROTLI_PARAM_QUALITY]: 11 },
        }).length,
    };
}

// The bundles themselves are build output and are not committed — they are
// regenerated by `npm run build`. The sizes are a finding, so they live in
// results/ alongside the timings.
await mkdir(join(here, 'results'), { recursive: true });
await writeFile(
    join(here, 'results', 'payload-sizes.json'),
    JSON.stringify(report, null, 2) + '\n',
);

const kb = (n) => `${(n / 1024).toFixed(1)} kB`;
console.log('bundle'.padEnd(12), 'minified'.padStart(11), 'gzip'.padStart(11), 'brotli'.padStart(11));
for (const [name, r] of Object.entries(report)) {
    console.log(name.padEnd(12), kb(r.minified).padStart(11), kb(r.gzip).padStart(11), kb(r.brotli).padStart(11));
}
