// <auto-generated />
using System;
using FamilyTree.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyTree.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FamilyTreeDbContext))]
    [Migration("20260503103937_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("FamilyTree.Domain.Entities.AdoptiveParentChild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId", "ChildId")
                        .IsUnique();

                    b.ToTable("AdoptiveParentChildLinks");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.BiologicalParentChild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId", "ChildId")
                        .IsUnique();

                    b.ToTable("BiologicalParentChildLinks");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.Marriage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndReason")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Spouse1Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Spouse2Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartPlace")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Spouse1Id");

                    b.HasIndex("Spouse2Id");

                    b.ToTable("Marriages");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthSurname")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeathPlace")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.StepparentRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarriageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StepchildId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StepparentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarriageId");

                    b.HasIndex("StepchildId");

                    b.HasIndex("StepparentId", "StepchildId", "MarriageId")
                        .IsUnique();

                    b.ToTable("StepparentRelationships");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.AdoptiveParentChild", b =>
                {
                    b.HasOne("FamilyTree.Domain.Entities.Person", "Child")
                        .WithMany("AdoptiveParentLinks")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTree.Domain.Entities.Person", "Parent")
                        .WithMany("AdoptiveChildLinks")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FamilyTree.Domain.ValueObjects.PartialDate", "AdoptionDate", b1 =>
                        {
                            b1.Property<Guid>("AdoptiveParentChildId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Day")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AdoptionDate_Day");

                            b1.Property<bool>("IsApproximate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AdoptionDate_IsApproximate");

                            b1.Property<int?>("Month")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AdoptionDate_Month");

                            b1.Property<int>("Year")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AdoptionDate_Year");

                            b1.HasKey("AdoptiveParentChildId");

                            b1.ToTable("AdoptiveParentChildLinks");

                            b1.WithOwner()
                                .HasForeignKey("AdoptiveParentChildId");
                        });

                    b.Navigation("AdoptionDate");

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.BiologicalParentChild", b =>
                {
                    b.HasOne("FamilyTree.Domain.Entities.Person", "Child")
                        .WithMany("BiologicalParentLinks")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTree.Domain.Entities.Person", "Parent")
                        .WithMany("BiologicalChildLinks")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.Marriage", b =>
                {
                    b.HasOne("FamilyTree.Domain.Entities.Person", "Spouse1")
                        .WithMany("MarriagesAsSpouse1")
                        .HasForeignKey("Spouse1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTree.Domain.Entities.Person", "Spouse2")
                        .WithMany("MarriagesAsSpouse2")
                        .HasForeignKey("Spouse2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FamilyTree.Domain.ValueObjects.PartialDate", "EndDate", b1 =>
                        {
                            b1.Property<Guid>("MarriageId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Day")
                                .HasColumnType("INTEGER")
                                .HasColumnName("EndDate_Day");

                            b1.Property<bool>("IsApproximate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("EndDate_IsApproximate");

                            b1.Property<int?>("Month")
                                .HasColumnType("INTEGER")
                                .HasColumnName("EndDate_Month");

                            b1.Property<int>("Year")
                                .HasColumnType("INTEGER")
                                .HasColumnName("EndDate_Year");

                            b1.HasKey("MarriageId");

                            b1.ToTable("Marriages");

                            b1.WithOwner()
                                .HasForeignKey("MarriageId");
                        });

                    b.OwnsOne("FamilyTree.Domain.ValueObjects.PartialDate", "StartDate", b1 =>
                        {
                            b1.Property<Guid>("MarriageId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Day")
                                .HasColumnType("INTEGER")
                                .HasColumnName("StartDate_Day");

                            b1.Property<bool>("IsApproximate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("StartDate_IsApproximate");

                            b1.Property<int?>("Month")
                                .HasColumnType("INTEGER")
                                .HasColumnName("StartDate_Month");

                            b1.Property<int>("Year")
                                .HasColumnType("INTEGER")
                                .HasColumnName("StartDate_Year");

                            b1.HasKey("MarriageId");

                            b1.ToTable("Marriages");

                            b1.WithOwner()
                                .HasForeignKey("MarriageId");
                        });

                    b.Navigation("EndDate");

                    b.Navigation("Spouse1");

                    b.Navigation("Spouse2");

                    b.Navigation("StartDate")
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.Person", b =>
                {
                    b.OwnsOne("FamilyTree.Domain.ValueObjects.PartialDate", "BirthDate", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Day")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BirthDate_Day");

                            b1.Property<bool>("IsApproximate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BirthDate_IsApproximate");

                            b1.Property<int?>("Month")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BirthDate_Month");

                            b1.Property<int>("Year")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BirthDate_Year");

                            b1.HasKey("PersonId");

                            b1.ToTable("People");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("FamilyTree.Domain.ValueObjects.PartialDate", "DeathDate", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Day")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DeathDate_Day");

                            b1.Property<bool>("IsApproximate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DeathDate_IsApproximate");

                            b1.Property<int?>("Month")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DeathDate_Month");

                            b1.Property<int>("Year")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DeathDate_Year");

                            b1.HasKey("PersonId");

                            b1.ToTable("People");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("BirthDate");

                    b.Navigation("DeathDate");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.StepparentRelationship", b =>
                {
                    b.HasOne("FamilyTree.Domain.Entities.Marriage", "Marriage")
                        .WithMany("StepparentRelationships")
                        .HasForeignKey("MarriageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTree.Domain.Entities.Person", "Stepchild")
                        .WithMany("StepchildLinks")
                        .HasForeignKey("StepchildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTree.Domain.Entities.Person", "Stepparent")
                        .WithMany("StepparentLinks")
                        .HasForeignKey("StepparentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marriage");

                    b.Navigation("Stepchild");

                    b.Navigation("Stepparent");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.Marriage", b =>
                {
                    b.Navigation("StepparentRelationships");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.Person", b =>
                {
                    b.Navigation("AdoptiveChildLinks");

                    b.Navigation("AdoptiveParentLinks");

                    b.Navigation("BiologicalChildLinks");

                    b.Navigation("BiologicalParentLinks");

                    b.Navigation("MarriagesAsSpouse1");

                    b.Navigation("MarriagesAsSpouse2");

                    b.Navigation("StepchildLinks");

                    b.Navigation("StepparentLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
